name: doit

# See docs
# https://melos.invertase.dev/

packages:
  - packages/*
  - .

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    usePubspecOverrides: true

ide:
  intellij: true
  vscode: true

scripts:
  postbootstrap: cd packages/localization && melos gen-l10n

  gen-code:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on: build_runner

  gen-code:all:
    run: melos run gen-code --no-select
    description: Run `gen-code` for each package


  analyze:
    exec: flutter analyze
    description: Run `flutter analyze` in all packages

  format:
    exec: flutter format --line-length=100 ./
    description: Run `flutter format` in all packages

  test:
    # Only run the test command when the package has a test directory
    run: melos exec --dir-exists=test -- "flutter test"
    description: Run `flutter test` in all packages

  gen-l10n:
    exec: flutter gen-l10n && flutter format --line-length=100 ./
    description: Run `flutter gen-l10n` in `localization` package
    select-package:
      scope: "localization"
  test-g:
    run: melos exec --depends-on="test_ui_utils" -- "flutter test --tags=golden"
    description: Run `flutter test` in all packages

  test-g-u:
    run: melos exec --depends-on="test_ui_utils" -- "flutter test --update-goldens --tags=golden"
    description: Run `flutter test` in all packages

