// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmgfHTWYtMmSkJzTJISj3xchKpW2CFvtA',
    appId: '1:708438817369:web:4f8c01367b40acf7064f48',
    messagingSenderId: '708438817369',
    projectId: 'doit-b6734',
    authDomain: 'doit-b6734.firebaseapp.com',
    storageBucket: 'doit-b6734.appspot.com',
    measurementId: 'G-HL4PRDL2W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYkDVQCBdcmI4ywS5RVECbfLSErfjAoLA',
    appId: '1:708438817369:android:7642217a99104f95064f48',
    messagingSenderId: '708438817369',
    projectId: 'doit-b6734',
    storageBucket: 'doit-b6734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Bu5v3kuofAsysuUceujljsdZXA9jXOw',
    appId: '1:708438817369:ios:3b2247e3f8844954064f48',
    messagingSenderId: '708438817369',
    projectId: 'doit-b6734',
    storageBucket: 'doit-b6734.appspot.com',
    iosClientId: '708438817369-04ag2912sjuig30124p3g61b7cfeimdq.apps.googleusercontent.com',
    iosBundleId: 'com.alexeykatsuro.doit',
  );
}
